# Model on `train`

Set the control parameters.

```{r}
ctrl <- trainControl(method = "cv",
                     number = 10,
                     classProbs=TRUE,
                     savePredictions = TRUE,
                     allowParallel = FALSE)
```

Set the model.

```{r}
library(xgboost)
method <- "xgbLinear"
```

Set the tuning grid for model `r method`.

```{r, eval = TRUE}
grid <- expand.grid(nrounds = seq(20, 100, 20), 
                    max_depth = 1, 
                    eta = seq(0.1, 0.3, 0.1), 
                    gamma = 0, 
                    colsample_bytree = seq(0.2, 0.5, 0.1), 
                    min_child_weight = 1)
```

Fit model over the tuning parameters.

```{r}
trainingModel <- train(type ~ .,
                       data = select(train, -matches("id")),
                       method = method,
                       trControl = ctrl,
                       # tuneGrid = grid,
                       nthreads = 3)
```

Evaluate the model on the training dataset.

```{r tuningTraining}
trainingModel
ggplot(trainingModel) + theme_bw()
hat <-
  train %>%
  transform(hat = predict(trainingModel, train)) %>%
  select(matches("type|hat"))
postResample(hat$hat, hat$type)
confusionMatrix(hat$hat, hat$type)
varImp(trainingModel)
```

Display the final model.

```{r, eval = FALSE}
trainingModel$finalModel
```
